Blog/Controllers/CategoryController.cs
using Blog.Contrats;
using Blog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Blog.Contrats.IServiceCategory;

namespace Blog.Controllers
{
    [Authorize (Roles ="Administrador")]
    public class CategoryController : Controller
    {
    
        private readonly IServicesCategories categoryService;
        public CategoryController(IServicesCategories categoryService)
        {
            this.categoryService = categoryService; 
        }

       
        public ActionResult Index()
        {
            var categories = categoryService.GetCategories();

            IList<CategoryModel> categories1 = new List<CategoryModel>();

            foreach (var cat in categories)
            {
                var creada = new CategoryModel { Id = cat.Id, Active = cat.Active, Description = cat.Description, Name = cat.Name };
                categories1.Add(creada);
            }

            return View(categories1);
        }  

        public ActionResult Create()
        {
            return View();
        } 

       
        public ActionResult Delete(int id)
        {
            categoryService.EditCategory(categoryService.SearchCategory(id), true);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoryModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var category = new Category { Id = model.Id, Active = model.Active, Description = model.Description, Name = model.Name };
            categoryService.SaveCategory(category);

            return RedirectToAction("Index");

        }
        
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var category = categoryService.SearchCategory(id); 

            return View(new CategoryModel {Id = category.Id, Name = category.Name, Active = category.Active, Description = category.Description}); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoryModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var category = new Category { Id = model.Id, Active = model.Active, Description = model.Description, Name = model.Name };

            categoryService.EditCategory(category,false);

            return RedirectToAction("Index");
        }

    }
}

Blog/Controllers/CommentController.cs
using Blog.Contrats;
using Blog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Blog.Contrats.IServiceComment;

namespace Blog.Controllers
{
    [Authorize(Roles ="Administrador")]
    public class CommentController : Controller
    {
        private readonly IServicesComments CommentService;

        public CommentController(IServicesComments CommentService)
        {
            this.CommentService = CommentService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var comments = CommentService.GetComments();

            IList<CommentModel> commentsModel = new List<CommentModel>();

            foreach (var item in comments)
            {
                var comment = new CommentModel()
                {
                    Description = item.Description,
                    Id = item.Id,
                    IdUser = item.IdUser,
                    IdNote = item.IdNote,
                    Active = item.Active
                };

                commentsModel.Add(comment);
            }


            return View(commentsModel);
        }


        public ActionResult Delete(int id)
        {
            if(CommentService.SearchComment(id) != null)
            {
                CommentService.Edit(CommentService.SearchComment(id), true);
            }

            return RedirectToAction("Index");
            
        }

        [HttpGet]
        public ActionResult Edit (int id)
        {
            Comment commentSearch = CommentService.SearchComment(id);
            var commentModel = new CommentModel()
            {
                Description = commentSearch.Description,
                Id = commentSearch.Id,
                IdUser = commentSearch.IdUser,
                IdNote = commentSearch.IdNote,
                Active = commentSearch.Active
            };

            return View(commentModel);
        }

        [HttpPost]
        public ActionResult Edit(CommentModel model)
        {
            var comment = new Comment()
            {
                Active = true,
                IdNote = model.IdNote,
                IdUser = model.IdUser,
                Description = model.Description
            };

            if (CommentService.Edit(comment, false))
            {
               return  RedirectToAction("Index");
            }

            return RedirectToAction("Edit", new { id = model.Id });

        }
    }
}

Blog/Controllers/NoteController.cs
using Blog.Contrats;
using Blog.Models;
using Blog.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Blog.Contrats.IServiceCategory;
using static Blog.Contrats.IServiceComment;
using static Blog.Contrats.IServiceNote;

namespace Blog.Controllers
{
    [Authorize(Roles ="Administrador")]      //Solo el usuario admin puede accerder a todoas las funciones. 
    public class NoteController : Controller
    {
        private readonly IServicesNotes NoteService;
        private readonly IServicesCategories CategoryService;
        private readonly IServicesComments CommentService;


        public NoteController(IServicesNotes NoteService, IServicesCategories CategoryService, IServicesComments CommentService)
        {
            this.NoteService = NoteService;
            this.CategoryService = CategoryService;
            this.CommentService = CommentService;
        }

        [AllowAnonymous] // el index puede ser accedido por todos los usuarios 
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var notes = NoteService.GetNotes();

                IList<NoteModel> notes1 = new List<NoteModel>();

                foreach (var not in notes)
                {
                    var creada = new NoteModel { Id = not.Id, Active = true, Description = not.Description.ToString(), Title = not.Title, Date = Convert.ToDateTime(not.Date.ToString()), IdCategory = not.IdCategory };
                    notes1.Add(creada);
                }

                return View(notes1);

            }
            return RedirectToAction("Login", "Account");
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var note = NoteService.SearchNotes(id);

            var listComments = new List<CommentModel>();
            foreach (var item in note.Comments)
            {
                var comment = new CommentModel();
                comment.Active = item.Active;
                comment.Description = item.Description;
                comment.Id = item.Id;
                comment.IdNote = item.IdNote;
                comment.IdUser = item.IdUser;

                listComments.Add(comment);
            }


            return View(new NoteModel { Id = note.Id, Date = note.Date, Title = note.Title, Active = note.Active, Description = note.Description, IdCategory = note.IdCategory, Commments = listComments });
        }

        public ActionResult IndexAdmin()
        {
            var notes = NoteService.GetNotes();

            IList<NoteModel> notes1 = new List<NoteModel>();

            foreach (var not in notes)
            {
                var creada = new NoteModel { Id = not.Id, Active = true, Description = not.Description, Title = not.Title, Date = not.Date.Date, IdCategory = not.IdCategory };
                notes1.Add(creada);
            }

            return View(notes1);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Categories = new SelectList(CategoryService.GetCategories().ToList(),
                                               nameof(Category.Id), nameof(Category.Name));
            return View();
        }

        public ActionResult Edit(int id)
        {
            var note = NoteService.SearchNotes(id);

            ViewBag.Categories = new SelectList(CategoryService.GetCategories().ToList(),
                                              nameof(Category.Id), nameof(Category.Name));

            return View(new NoteModel { Id = note.Id, Date = note.Date, Title = note.Title, Active = note.Active, Description = note.Description, IdCategory = note.IdCategory });

        }

        public ActionResult Delete(int id)
        {
            if (NoteService.Edit(NoteService.SearchNotes(id), true))
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(NoteModel model)
        {
            var note = new Note()
            {
                Active = true,
                Date = DateTime.Now,
                Title = model.Title,
                Description = model.Description,
                Id = model.Id,
                IdCategory = model.IdCategory

            };

            NoteService.Create(note);
            return RedirectToAction("Index");

        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(NoteModel model)
        {
            var note = new Note()
            {
                Active = true,
                Date = DateTime.Now,
                Title = model.Title,
                Description = model.Description.ToString(),
                Id = model.Id,
                IdCategory = model.IdCategory
            };

            if (NoteService.Edit(note, false))
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Comment(int id)
        {
            var model = new CommentModel();
            model.IdNote = id;
            model.Active = true;

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Comment(CommentModel model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var comment = new Comment()
                {
                    Active = true,
                    IdNote = model.IdNote,
                    IdUser = User.Identity.GetUserId(),
                    Description = model.Description
                };

                CommentService.AddComment(comment);
                return RedirectToAction("Index");
            }

            return RedirectToAction("Login", "Account");

        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Search()
        {
            var notes = NoteService.GetNotes();

            IList<NoteModel> notes1 = new List<NoteModel>();

            foreach (var not in notes)
            {
                var creada = new NoteModel { Id = not.Id, Active = true, Description = not.Description.ToString(), Title = not.Title, Date = Convert.ToDateTime(not.Date.ToString()), IdCategory = not.IdCategory };
                notes1.Add(creada);
            }

            return View(notes1);
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult NotesCategory(int id)
        {
            var notes = NoteService.GetNotesCategory(id);

            IList<NoteModel> notes1 = new List<NoteModel>();

            foreach (var not in notes)
            {
                var creada = new NoteModel { Id = not.Id, Active = true, Description = not.Description.ToString(), Title = not.Title, Date = Convert.ToDateTime(not.Date.ToString()), IdCategory = not.IdCategory };
                notes1.Add(creada);
            }

            return View(notes1);

        }
    }
}

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Layout.css" rel="stylesheet" />
</head>
<body> 

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("BLOG DEPORTIVO", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul id="menu" class="nav navbar-nav">
                        
                        <li class="dropdown navbar-btn ">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">
                                Comentarios<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Administrar", "Index", "Comment")</li>
                            </ul>
                        </li>
                        
                        <li class="dropdown navbar-btn ">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">
                                Categorias<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Categorias", "Index", "Category")</li>
                                <li>@Html.ActionLink("Crear", "Create", "Category")</li>
                                <li>@Html.ActionLink("Editar ", "Index", "Category")</li>
                            </ul>
                        </li>
                        

                        <li class="dropdown navbar-btn ">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">
                                Notas <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Notas", "Index", "Note")</li>
                                <li>@Html.ActionLink("Crear Nota", "Create", "Note")</li>
                                <li>@Html.ActionLink("Editar Notas", "IndexAdmin", "Note")</li>
                                <li>@Html.ActionLink("Buscar Notas", "Search", "Note")</li>
                            </ul>
                        </li>
                      

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Maximiliano Marín</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>